### ISSUE TITLE
Group Specs by Same Categories Used at W3C

### ISSUE THREAD

**Issue by rasamassen** [LeaVerou/css3test#94]
Sometimes I think CSS3Test is misleading because makes it look like browsers are expected to have these abilities implemented. Especially as more early stage standards are being added (scroll snaps was added within days of the 1st working draft being released).

I think it would be wise to group these tests by the same categories W3C uses at http://www.w3.org/Style/CSS/current-work :: Completed, Testing, Refining, etc. or Recommendation, Proposed Rec, Candidate Rec, Last Call, Working Draft (the second set is probably more clear language).

Simply grouping these spec tests by those categories would give people a lot more clear idea as to what they should be expecting browsers to have implemented in the first place and what to be watching for in the near future as opposed to thinking, "why doesn't my browser have scroll snaps implemented yet? what a horrible browser!"

**Comment by LeaVerou** [comment]
Grouping them by status is misleading, as there *are* specs that are still WD and browsers are generally expected (by authors) to have implemented them, e.g. transitions. Also, I think a deeper categorization of features (they’re already categorized by spec) will end up overcomplicating things for little benefit. Nobody thinks "What a horrible browser!" because their browser doesn't implement a certain feature, unless they’re utterly clueless. Instead, they would probably check first if *any* browser implements that feature and then draw conclusions.
